### ISSUE TITLE
Max backups being ignored

### ISSUE THREAD

**Issue by danmed** [danmed/TasmoBackupV1#13]
Thanks for looking into this! That delete backup option would be awesome.
- As for Max backups; i am using the backupall.php and its still surpassing the max backup count.  I even just pressed on the backup all button and it went past 5 even though my max is set to 5.

_Originally posted by @iptvcld in https://github.com/danmed/TasmoBackupV1/issues/10#issuecomment-584839795_

**Comment by danmed** [comment]
So far it seems that the maxbackup count is working.. i've set my minimum time to 1 hour so i will confirm soon.

**Comment by iptvcld** [comment]
Thanks; So in my test, i had the min time set to 0 and max backups set to 2.  I then pressed the backup all button a few times and the backups were going past the max count of 2

**Comment by danmed** [comment]
So i've just tested again with the min time set to 1 and it is adhering to my max backup count.
I then dropped the min time set to 0 as you have, and it's still adhering to it.

There is something else going on which i need to check though.. If you create an individual backup and then later run backup all, it deletes all but the last X (your max backup count)..

**Comment by iptvcld** [comment]
so i deleted the docker and started from the start. I have max hours set to 0, days set to 5 and max count set to 1 - pressed save
- Ran the backupall.php - showed 1 backup, ran the script again, showed 2. As per settings it should not have performed the 2nd backup

**Comment by iptvcld** [comment]
I just tested the below 

Backup All Min Hours: 0
Backup Max Days Old: 0
Backup Max Count: 2

And this works.. After the 2nd backup; if i press backup all the 3rd time, it will adhere to the max count of 2 and only keep 2 files (recent and the one before)

**Comment by danmed** [comment]
so.. it's working then?

**Comment by iptvcld** [comment]
With the above setup yes; and then i have my unRaid run the backupall.php script monthly.

**Comment by patrickdk77** [comment]
> so i deleted the docker and started from the start. I have max hours set to 0, days set to 5 and max count set to 1 - pressed save
> 
>     * Ran the backupall.php - showed 1 backup, ran the script again, showed 2. As per settings it should not have performed the 2nd backup

In this case it would backup.
it's Min Hours, so all backupall requests are honored.
Maybe the Max Days needs to be explained more.

If a backup is < max days old, or there are < max count backups, it is not deleted.
Considering Max Days was set to 5, no backups would be deleted till atleast they are 5days old, and then only if the total number of backups was over 1.

**Comment by patrickdk77** [comment]
Backups Min Hours limits backupall from backing up the same devices too many times in a given time period (one per day? or week)

Backups Max Days old, lets it delete any backups older than this if max count is 0, or current number of backups is > max count

Backups Max Count, lets it delete any backups exceed the requested count, if max days is 0, or only removed backups that are older than Max Days and exceed the count

Setting any of the above to 0, will cause it to disable that option.
If Max Days and Max Count are both 0, it will keep an unlimited number of backups.

My goal was to say, I want atleast a month history of backups, but I also want to make sure I always have atleast 3 backups of each device, no matter how old it is.
