### ISSUE TITLE
MQTT Scan / Add

### ISSUE THREAD

**Issue by marc-gist** [danmed/TasmoBackupV1#15]
How does this work? I use a non-standard mqtt topic `iot/tasmota/%prefix%/%topic%/`
I tried entering in `iot/tasmota` into the mqtt discover field, but nothing happens.

thanks!

**Comment by danmed** [comment]
Have you just tried leaving it as tasmota or tasmotas?

**Comment by marc-gist** [comment]
yes, its sending the wrong group toppic.

set at `tasmota` or whatever. send the group topic of
`tasmotas/cmnd/STATUS=5` to mqtt.
when it should be root\cmnd\tasmotas\STATUS=5
so if I tell it my root is `tasmota`
it should send
`tasmota/cmnd/tasmotas/STATUS=5`

**Comment by patrickdk77** [comment]
iot/tasmota/tasmotas assuming the grouptopic is still default.

**Comment by patrickdk77** [comment]
added config option for full control of topic and prefix
