### ISSUE TITLE
ip range Discovery not working (Hass.io - Unraid - Win Docker) 

### ISSUE THREAD

**Issue by balvant813** [danmed/TasmoBackupV1#16]
I am running hass.io (unraid -> docker/windows) and installed the tasmoback (1.02).

It does NOT Discover tasmota devices UNLESS I use ADD button to add them manually (hard to do when I have 50+ devices.) one by one!

Do have any idea why? range (e.g. 192.168.200.1-255) does not work?

Thanks

**Comment by danmed** [comment]
Are you sure you are leaving it long enough? It will take maybe 10 minutes
to scan a whole range like that.. Maybe try a smaller range?

**Comment by balvant813** [comment]
You are right! Just needed more time to discover!

 

Some suggestions:

1.	It will be helpful if  backup ‘DOWNLOAD’ – naming can include      IP  and/or device name 
2.	Some status indicator for ‘discover’, ‘Add’ actions

 

Great utility…

 

Thanks for all the work and sharing!

 

B Patel
