### ISSUE TITLE
Button Restore

### ISSUE THREAD

**Issue by ricain59** [danmed/TasmoBackupV1#24]
Hi,

First thank you for your work.
It's possible have a button "restore configuration" at side option download:
![image](https://user-images.githubusercontent.com/13002652/75611818-d8534c80-5b15-11ea-940c-f955c28715c5.png)

**Comment by danmed** [comment]
I assume you mean you want to be able to restore the backed up
configuration?

**Comment by ricain59** [comment]
Yes This is.
