### ISSUE TITLE
dark theme feature request

### ISSUE THREAD

**Issue by vMeph** [danmed/TasmoBackupV1#25]
would rox to have a dark theme option...
also would be nice to have a fancy icon for the addon, sense now all addons in HA have fancy icons

**Comment by patrickdk77** [comment]
The icons are done. The theme is causing me issues. I am in no way a css person though.

**Comment by vMeph** [comment]
the icon looks awesome thanks :)
hopefully you can come up with a solution for a dark theme and light theme(current style) option

**Comment by jorgeassuncao** [comment]
Plus one for that!

**Comment by patrickdk77** [comment]
added in 1.03.17
