### ISSUE TITLE
Backup path to write addons folder

### ISSUE THREAD

**Issue by MYLE-01** [danmed/TasmoBackupV1#26]
could the backup be written home assistant Config \ TasmoBackup

**Comment by patrickdk77** [comment]
I have no idea what that even means

**Comment by patrickdk77** [comment]
Closing due to lack of information.
writing backups to a configuration folder is a bad idea.
writing backups to the addons folder is already currently being done by default.

**Comment by xbmcnut** [comment]
Any chance the backups can be configured to write here? That would allow easy off-boarding to a safer location.

![image](https://user-images.githubusercontent.com/1492137/83622046-9c7fc580-a5e3-11ea-9df8-4e36dc98af7c.png)
