### ISSUE TITLE
Previous docker image is not being deleted after successful update

### ISSUE THREAD

**Issue by jorgeassuncao** [danmed/TasmoBackupV1#27]
The process of updating the addon is leaving the previous docker image after a successful update.

Before the update:
![1111](https://user-images.githubusercontent.com/7755388/76525203-4fb4a480-6463-11ea-8db5-c04a07fb997e.png)

After the update:
![2222](https://user-images.githubusercontent.com/7755388/76525231-5c38fd00-6463-11ea-80f1-194001ec31ee.png)

Previous images left behind:
![3333](https://user-images.githubusercontent.com/7755388/76525297-81c60680-6463-11ea-9768-22346459bf39.png)

**Comment by patrickdk77** [comment]
This is fixed now. I believe old versions will still have to be removed as it likely won't retroactively remove them.
