### ISSUE TITLE
Tasmo backup can not be installed sinds update to 1.3.13

### ISSUE THREAD

**Issue by patrickvanhattem** [danmed/TasmoBackupV1#29]
Tasmo backup cannot be installed on Hassio.
hassio says there is a update 1.3.13 gutt there is no update to 1.3.13

log error:
20-03-23 07:45:19 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install danmed/tasmobackupv1:1.03.13 -> 404 Client Error: Not Found ("manifest for danmed/tasmobackupv1:1.03.13 not found: manifest unknown: manifest unknown").

**Comment by brinzlee** [comment]
Same issue here.....press update button and nothing happens when upgrading from 1.03.12 to 1.03.13

**Comment by patrickdk77** [comment]
It's fixed, forgot to push the compiled version
