### ISSUE TITLE
Bundle external sources

### ISSUE THREAD

**Issue by newhinton** [danmed/TasmoBackupV1#3]
Quiet useful!
However, currently this service makes requests to:
ajax.googleapis.com
bootstrapcdn.com
datatables.com
googletagmanager.com

I dont think this app requires any of the above to be external, especially the tracking. Could you bundle bootstrap and such together so that this app is still usable in a network that does not allow connections to those sites?

**Comment by danmed** [comment]
Good point, thanks for pointing it out. I'll get that worked on.

**Comment by danmed** [comment]
Latest commit moves all bootstrap resources into container.

**Comment by newhinton** [comment]
Great! 

On a sidenote, do you want a more technical review? (you asked on reddit for feedback)
I could give you some hints on how to improve one or two things, if you want help. (I could also help you out here and there, if you want that)

**Comment by danmed** [comment]
Hey, i've got a guy helping me optimise things already but i'm open to any and all ideas in theory :)

just working on exporting and importing to and from csv at the moment.

**Comment by danmed** [comment]
thanks for the hints. I know my structure and code is all over the place and the other guy i periodically cleaning it up. To be honest i'm close to having this as far as i'm going to take it other than a couple of extra features.. but i'll keep what you've said in mind.
