### ISSUE TITLE
Device name VS Friendly Name

### ISSUE THREAD

**Issue by dovrose** [danmed/TasmoBackupV1#35]
Hi,
I updated my Tasmota to 8.3.1 and the new future is "Device Name", and now TasmoBackupV1 pick up my Friendly Name 1, witch isn't currect, I also use SO19.
can you change (or add option for Tasmota version grater then 8.3) to use it insted.
Thank you,
Dov

**Comment by patrickdk77** [comment]
Yes, I was working on this.
Released in 1.03.18
