### ISSUE TITLE
Icon not displaying in unraid docker after last update.

### ISSUE THREAD

**Issue by iptvcld** [danmed/TasmoBackupV1#36]
attached
![dock1](https://user-images.githubusercontent.com/34818686/82719749-65bcbd80-9c7b-11ea-85f5-fed0d8e983ca.JPG)

**Comment by patrickdk77** [comment]
It's linked to a file that was moved, to sort things better.
I have put the image back so it should display fine now, or if not, shortly.

**Comment by iptvcld** [comment]
Sorry still did not work

**Comment by patrickdk77** [comment]
Can you compare your unraid template to this one:
https://github.com/digiblur/unraid-docker-templates/blob/master/tasmobackup.xml

This was the missing file, that loads correctly currently.
https://raw.githubusercontent.com/danmed/TasmoBackupV1/master/TasmoBackup.png

Can you post your template and I can see if I can figure it out. It's the only change that was made, and I don't have unraid to play with.

**Comment by iptvcld** [comment]
this is what it says icon URL - https://raw.githubusercontent.com/danmed/TasmoBackupV1/master/TasmoBackup.png

**Comment by iptvcld** [comment]
and yet it works if i click it
but does not show in unraid
where do i check my templates?

**Comment by patrickdk77** [comment]
I have no idea, I don't have unraid, and no plans to use it.
It's out of scope, but considering the icon did move, I put it back to fix this issue. It's likely unraid is caching it, cause it was moved a month ago. If this just started happening, it could be awhile before unraid cache expires and fixes itself.

**Comment by iptvcld** [comment]
it happened as soon as i updated. it is not a cache issue as i tried from incognito.

**Comment by iptvcld** [comment]
thats ok; thank you

**Comment by patrickdk77** [comment]
According to my 2min on google, it's a unraid cache issue.

https://forums.unraid.net/topic/73554-docker-icons-missing/

unraid downloads the images on reboots, and caches them.
How much you trust random threat on the internet is different.

**Comment by patrickdk77** [comment]
I think you are confusing browser cache with unraid icon caching.

**Comment by iptvcld** [comment]
Thanks got it.. I ended up removing the icon url and then reapply the url. Thank you for quick support as always
