### ISSUE TITLE
localhost name resolution

### ISSUE THREAD

**Issue by hobiga** [danmed/TasmoBackupV1#39]
When deploying on a Kubernetes cluster I noticed that it was the container would start up and then after a bit enter a  CrashLoopBackOff State.  I did some debugging and it has to do with the wait-for-it.sh script looking at localhost and port 9000.  When pinging the localhost it would always come back with the IPv6 address.  The /etc/php7/php-fpm.d/www.conf file is configured to listen on ip 127.0.0.1 and port 9000 so when the wait-for-it.sh script executes it's not trying the IPv4 address causing the wait-for-it.sh script to fail.

To fix it I removed the IPv6 line from the  /etc/hosts.

**Comment by patrickdk77** [comment]
This should be all corrected in 1.03.20

**Comment by patrickdk77** [comment]
I have redone this support again, as my previous fix was to change everything to 127.0.0.1, but I think I remember someone running ipv6 only containers had an issue with that. So I switched everything to use localhost, and did a solution much like lynema did. I test ipv4 and ipv6 localhost, and disable one if it isn't working. I've stood up some ipv6 containers to test on and my testing looks ok. But if anyone wants to test I can point you ad an image: docker pull patrickdk/tasmobackupv1:1.04.12
