### ISSUE TITLE
Tasmota 9.0.0.2 does not support Status command without a parameter

### ISSUE THREAD

**Issue by pcdiem** [danmed/TasmoBackupV1#43]
A commit to Tasmota on 10/5 made the Status command require a parameter. arendst verified that was a desired result of the commit.

**Comment by patrickdk77** [comment]
looking at the code looks like they really changed this up and it's not going to be backwards compatible. I'll get a device upgrade to test with.

Older versions (8.5.0) I can get the same info using status 9
But on the current version, if you don't use status 9 is for energy monitoring instead.

**Comment by patrickdk77** [comment]
This is resolved in 1.04.01
