### ISSUE TITLE
Editing Name always fails with "Error updating record for ..."

### ISSUE THREAD

**Issue by linuxguygary** [danmed/TasmoBackupV1#45]
Attempting to edit a name , (rather than remove and re-add the device)  always results in an error message.  

E.G.
**Error updating record for 192.168.20.154 PlugA Spare**

Backups work fine,  I can remove / re-add  without issues. 

Using latest release,  version: 1.04.02

**Comment by patrickdk77** [comment]
Fixed in 1.04.06
