### ISSUE TITLE
Auto Backup Failing

### ISSUE THREAD

**Issue by danmed** [danmed/TasmoBackupV1#48]
127.0.0.1 - - [03/Feb/2021:13:08:00 +0000] "GET /backupall.php?docker=true HTTP/1.1" 500 5 "-" "Wget" "-" 0.002 0.000 . -
2021/02/03 13:08:00 [error] 51#51: *227 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function setupMQTT() in /var/www/html/lib/functions.inc.php:369
Stack trace:
#0 /var/www/html/backupall.php(5): backupAll(true)
#1 {main}
  thrown in /var/www/html/lib/functions.inc.php on line 369" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /backupall.php?docker=true HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function setupMQTT() in /var/www/html/lib/functions.inc.php:369
Stack trace:
#0 /var/www/html/backupall.php(5): backupAll(true)
#1 {main}
  thrown in /var/www/html/lib/functions.inc.php on line 369

**Comment by patrickdk77** [comment]
was fixed in 1.04.07
