### ISSUE TITLE
Feature request: Could TasmoBackup in the future, include -

### ISSUE THREAD

**Issue by jrho2** [danmed/TasmoBackupV1#51]
- EspHomeBackup? I have a lot of Sonoff switches, half of them ESP-Home, half tasmota, both of them dissapear on reinstall of homeassistant, so at the moment i have a handfull of devices which isnt visible in HomeAssisstant, which is annoying.

If TasmoBackup could find both systems, it would be great, and then I might put tasmota on them all - its exactly this find all functionality im missing! (o;

TasmoBackup is an important innovation, and things take time, but if you would consider this new functionality i would be gratefull!

**Comment by patrickdk77** [comment]
There is no way and no need to backup esphome devices. Every esphome device is built from a yaml file that is already backedup on the system you used to build the firmware. If your using the HomeAssistant esphome addon, then your HomeAssistant backups will automatically backup the esphome configurations.

If your using esphome some other way, not as an HomeAssistant addon, you would have to find another way to backup the esphome configs, but then the same would be true of tasmobackups also.
