### ISSUE TITLE
[FR]  Add-on Logo

### ISSUE THREAD

**Issue by SirGoodenough** [danmed/TasmoBackupV1#54]
I have been really sad looking at the tasmobackup add-in and not seeing a logo.  Because you have not set the logo to be shown, all we see is a weird green puzzle piece.  I see you have a logo in your repo here, so it does exist.
In case you did not have a logo I built one you can have as well.  Which ever logo you want to connect to this great software, you really should add it to the add-in so it shows up in the menu's (on the left side) and in the supervisor grid.

![tasmobackup_logo](https://user-images.githubusercontent.com/47349533/119913912-bfa63200-bf24-11eb-9180-072b51c10c80.jpg)

![tasmobackup_logo](https://user-images.githubusercontent.com/47349533/119913913-c03ec880-bf24-11eb-9be2-a0a3a6bcdd98.png)

![Screenshot_2021-05-27_19-50-58](https://user-images.githubusercontent.com/47349533/119914050-07c55480-bf25-11eb-9793-27385a0371e3.png)

![Screenshot_2021-05-27_19-51-53](https://user-images.githubusercontent.com/47349533/119914065-0eec6280-bf25-11eb-8f8b-511d7f2eb151.png)

**Comment by patrickdk77** [comment]
this is sad. i have overlooked that and didnt notice those icons over there. i have a realease i have been attempting to push for a few months. nithing critical in it. just a lot of clranup and some e tra safety checks.  ill get this added and push it out.

**Comment by SirGoodenough** [comment]
The Icon's look awesome!
BTW, FYI,  just found out that if you remove the repo's from the supervisor addon store, you also don't get update notifications from the supervisor, so if someone tells you about that problem, make sure they have your repo in the addon store.
