### ISSUE TITLE
Home Assistant Install Failure

### ISSUE THREAD

**Issue by KJThaDon** [danmed/TasmoBackupV1#58]
When adding the custom repo to home assistant, it throws the error
"Repostitory structure for master is not compliant"

**Comment by patrickdk77** [comment]
Do you have a screen shot of this?
The only thing I can locate that produces this message is HACS, and this is not a HACS module, so that wouldn't work.

This project is a HomeAssistant addon and needs to be installed using supervisor (or one of the alternative methods), not an intergration.

**Comment by KJThaDon** [comment]
> Do you have a screen shot of this?
> The only thing I can locate that produces this message is HACS, and this is not a HACS module, so that wouldn't work.
> 
> This project is a HomeAssistant addon and needs to be installed using supervisor (or one of the alternative methods), not an intergration.

My mistake. I was attempting to install through HACS. Thank you
