### ISSUE TITLE
Feature Request - Display MAC address with IP or in own column

### ISSUE THREAD

**Issue by marc-gist** [danmed/TasmoBackupV1#60]
I recently had a number of devices reset themselves.  So went to restore backups, which worked well, thank you!
However, what didn't work well, since the devices reset, their names were not what TasmoBackup displays, but the tasmota-XXXXX format on WiFi.  Would be great if I could easily see which device that is based on a search (mac address info when you click the name of the device in TasmoBackup isn't found).  Or simply displaying under the IP address, or in its own column in the gui would be great!

Thank you

**Comment by patrickdk77** [comment]
Resolved in 1.04.17

**Comment by marc-gist** [comment]
can we also get a docker update please :D

**Comment by patrickdk77** [comment]
I'm not sure what your asking about.

Docker images have been out for days now:
https://hub.docker.com/r/danmed/tasmobackupv1/tags?page=1&ordering=last_updated

Quoting Marc ***@***.***>:
