### ISSUE TITLE
9.5.0.6 (tasmota) dont do backups 

### ISSUE THREAD

**Issue by WarLion** [danmed/TasmoBackupV1#61]
i just notice that if you upgrade to 9.5.0.6  the backups fail , not sure if is only on my end but my devices with 9.5.0.3 tasmota the backups made it , , for testing just upgrade one of my 9.5.0.3 to 9.5.0.6 and now the backup fails

**Comment by patrickdk77** [comment]
This appears to be intentional, check out the new so128 option that causes the rejections when using 9.5.0.6 without a password.

**Comment by patrickdk77** [comment]
Resolved in 1.04.20

**Comment by WarLion** [comment]
thanks Patrick you are right
