### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase. See 'docker run --help'.

### ISSUE THREAD

**Issue by albilia** [danmed/TasmoBackupV1#63]
I managed to install some images on synology docker successfully, and for some reason can not figure out how to install TasmoBackupV1 on synology docker. Attach an image file with the error message I get. I would love to understand where I am wrong.
I would be happy if it would be possible to get some Command to Putty to install the image. Or any other simple and understandable way. Thanks in advance for the successful work with the repo : )
![docker error](https://user-images.githubusercontent.com/21350120/132776522-fe7001e9-e7bc-4465-80c1-21129ac2632c.png)

**Comment by patrickdk77** [comment]
installing the image wont help, your missing a -e before MYSQL_PASSWORD
