### ISSUE TITLE
Device discovery should update the version

### ISSUE THREAD

**Issue by ikarisan** [danmed/TasmoBackupV1#68]
Hi!

I scanned my network for Tasmota devices (v9.5.0) and added all of them to the list.
After that I updated all discovered to version 10.0.0 and did a rescan. But the version column still shows version 9.5.0. 
So I had to manually remove all twenty devices one by one to get an updated list. 

Maybe there should be a "rescan" button for existing devices. :)

**Comment by danmed** [comment]
On the next backup they will be updated

**Comment by patrickdk77** [comment]
It depends on the scan type. On a mqtt scan, it receives the version info when it scans, and it will update it. If you do an ip scan, it takes extra work to fetch the version and name, so it doesn't update on that case when it does a scan.

It is always updated when it does a backup.
