### ISSUE TITLE
Backup All observation

### ISSUE THREAD

**Issue by Hunterdiver** [danmed/TasmoBackupV1#70]
Hi,

I have been using this for a while with no major issues, I added 4 new devices and did a backup all with no problem,
I then did some tuning on the 4 new devices and clicked on backup all and although it reported back all backups completed successfully, no backups were created, and the counter was not incremented.

Individual backups work fine.

If I add a new device and select backup all the new device is backed up, but the existing ones are not backed up.

Is this by design ?

would it be possible to add a check box in the delete section so I can delete multiple backups  per device ?

Regards

Hunterdiver

**Comment by FlorianDessloch** [comment]
What's your setting for "Backup-All Min Hours between backups"?
Iassume the "Backup All" Button does not ignore this value.
The individual Buttons do ignore it, so you can make a backup prior to changing something.

**Comment by patrickdk77** [comment]
Working as expected, backupall only backups once per timeframe, and you have to use the indivitial backup button to override it.
