### ISSUE TITLE
Bug: List of IP's not sorting numerically

### ISSUE THREAD

**Issue by MaxVonEvil** [danmed/TasmoBackupV1#91]
As subject says, appears to be an alphabetical sort currently 
This is what I'm seeing:

![image](https://github.com/danmed/TasmoBackupV1/assets/19863636/5b08b0b1-3d3e-4dec-bc7e-f4e9606ee269)

Would have expected:

10.7.0.1
10.7.0.2
10.7.0.3
...

Thanks otherwise for a great project!

**Comment by patrickdk77** [comment]
should be all fixed, not sure how it got broken, but found lots of other sorting related things that needed adjustments too.
