### ISSUE TITLE
MYSQL authentication method

### ISSUE THREAD

**Issue by reebderdieb** [danmed/TasmoBackupV1#97]
MySQL server is moving away from native_password_authentication. Just upgraded my server to MySQL 9 and it dropped support for the native password plugin, just caching_sha2_password is supported. Perhaps you want to take that into account in the next updates.

**Comment by patrickdk77** [comment]
This should be resolved in 1.6.7
Though, if your running 32bit arm, it will not be resolved, and wont be, since 32bit arm has no 64bit time support
