### ISSUE TITLE
"add single device" missing

### ISSUE THREAD

**Issue by 7542** [danmed/TasmoBackupV1#98]
Version  1.06.07

I do not have "add single device"
also "dicover" worked only one time ... no rediscovery of full range possible? to get additional devices

**Comment by patrickdk77** [comment]
I have no idea what your asking about. There is no add single device or rediscovery buttons.

**Comment by 7542** [comment]
unfortunately there is no "add single device"-Button and also yes no "redescovery"-button.
ip-discovery worked one time and fetched my aktuual devices. now i have 3 new devices ... still functional in tasmoadmin ... but i can not fetch them in redoing "ip-discovery"! neither single ip or whole range.

**Comment by 7542** [comment]
if i do ... i get blank screen ... only refreching homeassistant url does restart tasmobackup-view.
full-reload (dev-tools) and hass-IO restart still done.

**Comment by 7542** [comment]
backup-function works

**Comment by 7542** [comment]
nobody any idea what is going wrong or what i am doing wrong?

**Comment by 7542** [comment]
please help

**Comment by 7542** [comment]
solved by updating to Version 1.06.08
